### ISSUE TITLE
 Uitleg tekst kleiner

### ISSUE THREAD

**Issue by slabarque** [slabarque/STUF#10]
![image](https://user-images.githubusercontent.com/2572680/37862462-7c7e632c-2f4d-11e8-99ed-26ecdb35db6a.png)

**Comment by stuFien** [comment]
Ook de tekst onder materialen. Maar misschien bespreken we dit beter eens in het echt? Alle tekst mogen in de verhouding van hoe ze nu staan wat kleiner worden. 
Ik bekijk dit wel vanop een 13-inch scherm. ik weet niet hoe de vergroting/verkleining precies werkt en welk effect dit heeft op andere schermgroottes maar jij weet hier waarschijnlijk wel raad me?
