### ISSUE TITLE
 vorige volgende: zonder pijltjes en wordt vorige object, volgende object

### ISSUE THREAD

**Issue by slabarque** [slabarque/STUF#12]
![image](https://user-images.githubusercontent.com/2572680/37862471-8e013a2a-2f4d-11e8-9f33-67868346ab34.png)

**Comment by slabarque** [comment]
Op de tekening ziet het eruit alsof ook de naam van het volgende/vorige object erbij moet staan. Is dat zo? Ik hoop dit dan niet te veel tekst wordt op kleinere schermen.

**Comment by stuFien** [comment]
Als de toevoeging het woord _object_  hinderend is (wegens te veel tekst) voor kleinere varianten van de site,  dan hoef je _object_ er niet bij te voegen.

dan verkiezen we de notatie zoals hieronder:

**< vorige, volgende >**


met 1 pijltje links van vorige en 1 pijltje rechts van volgende
