### ISSUE TITLE
 woorden storagespace aanpassen door juiste woorden

### ISSUE THREAD

**Issue by slabarque** [slabarque/STUF#13]
![image](https://user-images.githubusercontent.com/2572680/37862473-95b5f90e-2f4d-11e8-825d-ee8ab3e8d0f0.png)

**Comment by slabarque** [comment]
welke woorden moeten er dan waar komen?

**Comment by stuFien** [comment]
Kleerstaander, kledingrek 
Fruitschaal, schaal
OAT, opbergtafel
HOAT 1.0, opbergtafel/kruk
HOAT 2.0, opbergtafel/kruk
HOAT 3.0, opbergtafel/kruk

**extra opmerking**: Alle namen van de producten met een hoofdletter. Kleerstaander en Fruitschaal staan nu nog met een kleine letter.
