### ISSUE TITLE
Notie van de zin: Ontworpen en gemaakt in België.  Kan op maat besteld worden.

### ISSUE THREAD

**Issue by slabarque** [slabarque/STUF#18]
![image](https://user-images.githubusercontent.com/2572680/37862608-22ea8fa4-2f50-11e8-8ae5-738342c26707.png)

**Comment by slabarque** [comment]
wat word hier precies mee bedoeld? "Notie van de zin: Ontworpen en gemaakt in België. Kan op maat besteld worden."

**Comment by bmxpert** [comment]
kleine test van het replyen op een comment via reply op de mail
________________________________

**Comment by slabarque** [comment]
gewoon tekst iets kleiner
